### PR TITLE
fix code generation for new eslint

### PR DESCRIPTION
**Pull request by windwinkel**
### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Review by dniggemann — APPROVED** [review]

**Comment by windwinkel** [comment]
This is potentially unsafe, therefore this will be done in an extra ticket.

**Comment by pchorus** [comment]
@windwinkel Is there an extra ticket created? Why is it unsafe?

**Comment by windwinkel** [comment]
> @windwinkel Is there an extra ticket created? Why is it unsafe?

The resulting regex differ after your change, therefore good testing is needed. Since we need to change the openapi generator for fixing the `no-useless-escape` error, @dniggemann and I decided to drop this change for the time being and do both together. 
Ticket is: https://moneymeets.atlassian.net/browse/MD-6854

**Comment by pchorus** [comment]
I think it does not make much sense to combine both eslint rules and test them together, because `no-control-regex` can easily be fixed by the changes in this PR here. Of course, it needs testing, but that should not be a problem.

The other error `no-useless-escape` could only be fixed by changing the regexes in the api specs. I am not sure if that is possible at all.

So I would still prefer to finish and merge this PR here and have a look at the `no-useless-escape` later on.
Let's discuss this in our meeting this afternoon.

**Comment by pchorus** [comment]
As investigated with @windwinkel, this change is correct and it is even necessary.

Currently, the regex pattern is saved as a string with quotes. In this case, extra backslashes are needed to escape the backslash for the string so one backslash is kept, i.e. instead of `new RegExp(/^(application\/json|[^;/ \t]+\/[^;/ \t]+[+]json)[ \t]*(;.*)?$/, 'i');` it must have been `new RegExp(/^(application\/json|[^;/ \\t]+\/[^;/ \\t]+[+]json)[ \\t]*(;.*)?$/, 'i');` (changed `\t` to `\\t`).

This is not needed if regex pattern is defined using slashes, i.e. `new RegExp(/^(application\/json|[^;/ \t]+\/[^;/ \t]+[+]json)[ \t]*(;.*)?$/, 'i');`

Thus, I would like to merge changes as present in this PR.

**Review by pchorus — APPROVED** [review]

**Pull request merged**
